name:                discord-bot-v1
version:             0.1.0.0
github:              "rottensunday/discord-bot-v1"
license:             BSD3
author:              "rottensunday"
maintainer:          "arnachimm@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            fun

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rottensunday/discord-bot-v1#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- text
- unliftio
- sqlite-simple
- text-manipulate
- transformers

library:
  source-dirs: src

executables:
  discord-bot-v1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-bot-v1

tests:
  discord-bot-v1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - discord-bot-v1
    - HUnit
